name: Scoutsuite Analysis

on:
  push:
    branches:
      - develop
      - master

jobs:
  scoutsuite:
    runs-on: ubuntu-latest
    steps:
    # - name: Azure-Login
    #   uses: Azure/login@v1
    #   with:
    #     creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
    # # - run: |
    # #     az resource list
    - name: git clone
      run: |
        git clone https://github.com/colac/ScoutSuite.git
    - name: install requirements
      run: |
        cd ScoutSuite
        pip install -r requirements.txt
    - name: run scoutsuite
      run: |
        az login --service-principal -u ${{ secrets.ARM_CLIENT_ID }} -p ${{ secrets.ARM_CLIENT_SECRET }} --tenant ${{ secrets.ARM_TENANT_ID }}
        ls -la
        python3.8 ScoutSuite/scout.py azure --cli --no-browser --report-dir /scoutReport

    - name: Upload Report Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: scoutsuiteReport
        path: ./ScoutSuite/scoutReport # or path/to/artifact